name: claps_api_client
description: A repository to implement the Claps API.
version: 1.0.0+1
publish_to: none

environment:
  sdk: ">=2.17.0 <3.0.0"
  flutter: 3.0.5

dependencies:
  equatable: ^2.0.3
  flutter:
    sdk: flutter
  http: ^0.13.5

dev_dependencies:
  build_runner: ^2.2.0
  json_serializable: ^6.3.1
  very_good_analysis: ^3.0.1

