name: videos_repository
description: A repository to handle the Video domain.
version: 1.0.0+1
publish_to: none

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  freezed: ^2.1.0+1
  claps_api_client:
    path: ../claps_api_client

dev_dependencies:
  build_runner: ^2.2.0
  very_good_analysis: ^3.0.1

