name: the_feeder
description: A new Flutter project.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=2.17.6 <3.0.0"

dependencies:
  claps_api_client:
    path: packages/claps_api_client
  cupertino_icons: ^1.0.2
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.1
  freezed_annotation: ^2.1.0
  uuid: ^3.0.6
  video_player: ^2.4.7
  videos_repository:
    path: packages/videos_repository

dev_dependencies:
  build_runner: ^2.2.0
  freezed: ^2.1.0+1
  very_good_analysis: ^3.0.1

flutter:
  uses-material-design: true
